/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Persons implements Serializable {

    private static final long serialVersionUID = -131551244;

    private String id;
    private String name;
    private Byte   sex;
    private String areaid;
    private Long   birthday;

    public Persons() {}

    public Persons(Persons value) {
        this.id = value.id;
        this.name = value.name;
        this.sex = value.sex;
        this.areaid = value.areaid;
        this.birthday = value.birthday;
    }

    public Persons(
        String id,
        String name,
        Byte   sex,
        String areaid,
        Long   birthday
    ) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.areaid = areaid;
        this.birthday = birthday;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getSex() {
        return this.sex;
    }

    public void setSex(Byte sex) {
        this.sex = sex;
    }

    public String getAreaid() {
        return this.areaid;
    }

    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }

    public Long getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Persons (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(sex);
        sb.append(", ").append(areaid);
        sb.append(", ").append(birthday);

        sb.append(")");
        return sb.toString();
    }
}
