/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinceId implements Serializable {

    private static final long serialVersionUID = -645871027;

    private Integer provinceId;
    private String  provinceName;

    public ProvinceId() {}

    public ProvinceId(ProvinceId value) {
        this.provinceId = value.provinceId;
        this.provinceName = value.provinceName;
    }

    public ProvinceId(
        Integer provinceId,
        String  provinceName
    ) {
        this.provinceId = provinceId;
        this.provinceName = provinceName;
    }

    public Integer getProvinceId() {
        return this.provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    public String getProvinceName() {
        return this.provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProvinceId (");

        sb.append(provinceId);
        sb.append(", ").append(provinceName);

        sb.append(")");
        return sb.toString();
    }
}
