/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Records implements Serializable {

    private static final long serialVersionUID = 1828266751;

    private String barid;
    private String personid;
    private Long   onlinetime;
    private Long   offlinetime;

    public Records() {}

    public Records(Records value) {
        this.barid = value.barid;
        this.personid = value.personid;
        this.onlinetime = value.onlinetime;
        this.offlinetime = value.offlinetime;
    }

    public Records(
        String barid,
        String personid,
        Long   onlinetime,
        Long   offlinetime
    ) {
        this.barid = barid;
        this.personid = personid;
        this.onlinetime = onlinetime;
        this.offlinetime = offlinetime;
    }

    public String getBarid() {
        return this.barid;
    }

    public void setBarid(String barid) {
        this.barid = barid;
    }

    public String getPersonid() {
        return this.personid;
    }

    public void setPersonid(String personid) {
        this.personid = personid;
    }

    public Long getOnlinetime() {
        return this.onlinetime;
    }

    public void setOnlinetime(Long onlinetime) {
        this.onlinetime = onlinetime;
    }

    public Long getOfflinetime() {
        return this.offlinetime;
    }

    public void setOfflinetime(Long offlinetime) {
        this.offlinetime = offlinetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Records (");

        sb.append(barid);
        sb.append(", ").append(personid);
        sb.append(", ").append(onlinetime);
        sb.append(", ").append(offlinetime);

        sb.append(")");
        return sb.toString();
    }
}
