/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecordsPersons implements Serializable {

    private static final long serialVersionUID = 1690211527;

    private String personid;
    private String barid;
    private String name;
    private Byte   sex;
    private String areaid;
    private Long   birthday;

    public RecordsPersons() {}

    public RecordsPersons(RecordsPersons value) {
        this.personid = value.personid;
        this.barid = value.barid;
        this.name = value.name;
        this.sex = value.sex;
        this.areaid = value.areaid;
        this.birthday = value.birthday;
    }

    public RecordsPersons(
        String personid,
        String barid,
        String name,
        Byte   sex,
        String areaid,
        Long   birthday
    ) {
        this.personid = personid;
        this.barid = barid;
        this.name = name;
        this.sex = sex;
        this.areaid = areaid;
        this.birthday = birthday;
    }

    public String getPersonid() {
        return this.personid;
    }

    public void setPersonid(String personid) {
        this.personid = personid;
    }

    public String getBarid() {
        return this.barid;
    }

    public void setBarid(String barid) {
        this.barid = barid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getSex() {
        return this.sex;
    }

    public void setSex(Byte sex) {
        this.sex = sex;
    }

    public String getAreaid() {
        return this.areaid;
    }

    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }

    public Long getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RecordsPersons (");

        sb.append(personid);
        sb.append(", ").append(barid);
        sb.append(", ").append(name);
        sb.append(", ").append(sex);
        sb.append(", ").append(areaid);
        sb.append(", ").append(birthday);

        sb.append(")");
        return sb.toString();
    }
}
