/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecordsTime implements Serializable {

    private static final long serialVersionUID = -1245169630;

    private String  barid;
    private String  personid;
    private Long    internetTime;
    private Integer estimatedTime;

    public RecordsTime() {}

    public RecordsTime(RecordsTime value) {
        this.barid = value.barid;
        this.personid = value.personid;
        this.internetTime = value.internetTime;
        this.estimatedTime = value.estimatedTime;
    }

    public RecordsTime(
        String  barid,
        String  personid,
        Long    internetTime,
        Integer estimatedTime
    ) {
        this.barid = barid;
        this.personid = personid;
        this.internetTime = internetTime;
        this.estimatedTime = estimatedTime;
    }

    public String getBarid() {
        return this.barid;
    }

    public void setBarid(String barid) {
        this.barid = barid;
    }

    public String getPersonid() {
        return this.personid;
    }

    public void setPersonid(String personid) {
        this.personid = personid;
    }

    public Long getInternetTime() {
        return this.internetTime;
    }

    public void setInternetTime(Long internetTime) {
        this.internetTime = internetTime;
    }

    public Integer getEstimatedTime() {
        return this.estimatedTime;
    }

    public void setEstimatedTime(Integer estimatedTime) {
        this.estimatedTime = estimatedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RecordsTime (");

        sb.append(barid);
        sb.append(", ").append(personid);
        sb.append(", ").append(internetTime);
        sb.append(", ").append(estimatedTime);

        sb.append(")");
        return sb.toString();
    }
}
