/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SichuanProvince implements Serializable {

    private static final long serialVersionUID = 1761267070;

    private Integer areaid;
    private String  name;

    public SichuanProvince() {}

    public SichuanProvince(SichuanProvince value) {
        this.areaid = value.areaid;
        this.name = value.name;
    }

    public SichuanProvince(
        Integer areaid,
        String  name
    ) {
        this.areaid = areaid;
        this.name = name;
    }

    public Integer getAreaid() {
        return this.areaid;
    }

    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SichuanProvince (");

        sb.append(areaid);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
