/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo;


import cn.dyhack.barvisual.pojo.tables.Bars;
import cn.dyhack.barvisual.pojo.tables.BarsCopy;
import cn.dyhack.barvisual.pojo.tables.FloatPopulation;
import cn.dyhack.barvisual.pojo.tables.Persons;
import cn.dyhack.barvisual.pojo.tables.Province;
import cn.dyhack.barvisual.pojo.tables.Records;
import cn.dyhack.barvisual.pojo.tables.RecordsPersons;
import cn.dyhack.barvisual.pojo.tables.RecordsTime;
import cn.dyhack.barvisual.pojo.tables.SichuanProvince;
import cn.dyhack.barvisual.pojo.tables.Suspects;
import cn.dyhack.barvisual.pojo.tables.Total;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>internet_bar_backup</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BARS_PRIMARY = Indexes0.BARS_PRIMARY;
    public static final Index BARS_COPY_PRIMARY = Indexes0.BARS_COPY_PRIMARY;
    public static final Index FLOAT_POPULATION_AREAID = Indexes0.FLOAT_POPULATION_AREAID;
    public static final Index FLOAT_POPULATION_BARID = Indexes0.FLOAT_POPULATION_BARID;
    public static final Index FLOAT_POPULATION_BIRTHDAY = Indexes0.FLOAT_POPULATION_BIRTHDAY;
    public static final Index FLOAT_POPULATION_OFFLINETIME = Indexes0.FLOAT_POPULATION_OFFLINETIME;
    public static final Index FLOAT_POPULATION_ONLINETIME = Indexes0.FLOAT_POPULATION_ONLINETIME;
    public static final Index FLOAT_POPULATION_PERSONID = Indexes0.FLOAT_POPULATION_PERSONID;
    public static final Index PERSONS_B = Indexes0.PERSONS_B;
    public static final Index PERSONS_BIRTH = Indexes0.PERSONS_BIRTH;
    public static final Index PERSONS_ID = Indexes0.PERSONS_ID;
    public static final Index PERSONS_PRIMARY = Indexes0.PERSONS_PRIMARY;
    public static final Index PROVINCE_PRIMARY = Indexes0.PROVINCE_PRIMARY;
    public static final Index RECORDS_BARID = Indexes0.RECORDS_BARID;
    public static final Index RECORDS_PERSONID = Indexes0.RECORDS_PERSONID;
    public static final Index RECORDS_PERSONS_BARID = Indexes0.RECORDS_PERSONS_BARID;
    public static final Index RECORDS_PERSONS_PERSONID = Indexes0.RECORDS_PERSONS_PERSONID;
    public static final Index RECORDS_TIME_BARID = Indexes0.RECORDS_TIME_BARID;
    public static final Index RECORDS_TIME_INTERNET_TIME = Indexes0.RECORDS_TIME_INTERNET_TIME;
    public static final Index RECORDS_TIME_PERSONID = Indexes0.RECORDS_TIME_PERSONID;
    public static final Index SICHUAN_PROVINCE_PRIMARY = Indexes0.SICHUAN_PROVINCE_PRIMARY;
    public static final Index SUSPECTS_PRIMARY = Indexes0.SUSPECTS_PRIMARY;
    public static final Index TOTAL_AREAID = Indexes0.TOTAL_AREAID;
    public static final Index TOTAL_BARID = Indexes0.TOTAL_BARID;
    public static final Index TOTAL_BIRTHDAY = Indexes0.TOTAL_BIRTHDAY;
    public static final Index TOTAL_FLOAT_POPULATION = Indexes0.TOTAL_FLOAT_POPULATION;
    public static final Index TOTAL_NAME = Indexes0.TOTAL_NAME;
    public static final Index TOTAL_OFFLINETIME = Indexes0.TOTAL_OFFLINETIME;
    public static final Index TOTAL_ONLINETIME = Indexes0.TOTAL_ONLINETIME;
    public static final Index TOTAL_ONLINETIME_OFFLINETIME = Indexes0.TOTAL_ONLINETIME_OFFLINETIME;
    public static final Index TOTAL_PERSONID = Indexes0.TOTAL_PERSONID;
    public static final Index TOTAL_PRIMARY = Indexes0.TOTAL_PRIMARY;
    public static final Index TOTAL_SEX = Indexes0.TOTAL_SEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BARS_PRIMARY = Internal.createIndex("PRIMARY", Bars.BARS, new OrderField[] { Bars.BARS.ID }, true);
        public static Index BARS_COPY_PRIMARY = Internal.createIndex("PRIMARY", BarsCopy.BARS_COPY, new OrderField[] { BarsCopy.BARS_COPY.ID }, true);
        public static Index FLOAT_POPULATION_AREAID = Internal.createIndex("areaid", FloatPopulation.FLOAT_POPULATION, new OrderField[] { FloatPopulation.FLOAT_POPULATION.AREAID }, false);
        public static Index FLOAT_POPULATION_BARID = Internal.createIndex("barid", FloatPopulation.FLOAT_POPULATION, new OrderField[] { FloatPopulation.FLOAT_POPULATION.BARID }, false);
        public static Index FLOAT_POPULATION_BIRTHDAY = Internal.createIndex("birthday", FloatPopulation.FLOAT_POPULATION, new OrderField[] { FloatPopulation.FLOAT_POPULATION.BIRTHDAY }, false);
        public static Index FLOAT_POPULATION_OFFLINETIME = Internal.createIndex("offlinetime", FloatPopulation.FLOAT_POPULATION, new OrderField[] { FloatPopulation.FLOAT_POPULATION.OFFLINETIME }, false);
        public static Index FLOAT_POPULATION_ONLINETIME = Internal.createIndex("onlinetime", FloatPopulation.FLOAT_POPULATION, new OrderField[] { FloatPopulation.FLOAT_POPULATION.ONLINETIME }, false);
        public static Index FLOAT_POPULATION_PERSONID = Internal.createIndex("personid", FloatPopulation.FLOAT_POPULATION, new OrderField[] { FloatPopulation.FLOAT_POPULATION.PERSONID }, false);
        public static Index PERSONS_B = Internal.createIndex("b", Persons.PERSONS, new OrderField[] { Persons.PERSONS.BIRTHDAY }, false);
        public static Index PERSONS_BIRTH = Internal.createIndex("birth", Persons.PERSONS, new OrderField[] { Persons.PERSONS.BIRTHDAY }, false);
        public static Index PERSONS_ID = Internal.createIndex("ID", Persons.PERSONS, new OrderField[] { Persons.PERSONS.ID }, true);
        public static Index PERSONS_PRIMARY = Internal.createIndex("PRIMARY", Persons.PERSONS, new OrderField[] { Persons.PERSONS.ID }, true);
        public static Index PROVINCE_PRIMARY = Internal.createIndex("PRIMARY", Province.PROVINCE, new OrderField[] { Province.PROVINCE.AREAID }, true);
        public static Index RECORDS_BARID = Internal.createIndex("barid", Records.RECORDS, new OrderField[] { Records.RECORDS.BARID }, false);
        public static Index RECORDS_PERSONID = Internal.createIndex("personid", Records.RECORDS, new OrderField[] { Records.RECORDS.PERSONID }, false);
        public static Index RECORDS_PERSONS_BARID = Internal.createIndex("barid", RecordsPersons.RECORDS_PERSONS, new OrderField[] { RecordsPersons.RECORDS_PERSONS.BARID }, false);
        public static Index RECORDS_PERSONS_PERSONID = Internal.createIndex("personid", RecordsPersons.RECORDS_PERSONS, new OrderField[] { RecordsPersons.RECORDS_PERSONS.PERSONID }, false);
        public static Index RECORDS_TIME_BARID = Internal.createIndex("barid", RecordsTime.RECORDS_TIME, new OrderField[] { RecordsTime.RECORDS_TIME.BARID }, false);
        public static Index RECORDS_TIME_INTERNET_TIME = Internal.createIndex("internet_time", RecordsTime.RECORDS_TIME, new OrderField[] { RecordsTime.RECORDS_TIME.INTERNET_TIME }, false);
        public static Index RECORDS_TIME_PERSONID = Internal.createIndex("personid", RecordsTime.RECORDS_TIME, new OrderField[] { RecordsTime.RECORDS_TIME.PERSONID }, false);
        public static Index SICHUAN_PROVINCE_PRIMARY = Internal.createIndex("PRIMARY", SichuanProvince.SICHUAN_PROVINCE, new OrderField[] { SichuanProvince.SICHUAN_PROVINCE.AREAID }, true);
        public static Index SUSPECTS_PRIMARY = Internal.createIndex("PRIMARY", Suspects.SUSPECTS, new OrderField[] { Suspects.SUSPECTS.PERSONID }, true);
        public static Index TOTAL_AREAID = Internal.createIndex("areaid", Total.TOTAL, new OrderField[] { Total.TOTAL.AREAID }, false);
        public static Index TOTAL_BARID = Internal.createIndex("barid", Total.TOTAL, new OrderField[] { Total.TOTAL.BARID }, false);
        public static Index TOTAL_BIRTHDAY = Internal.createIndex("birthday", Total.TOTAL, new OrderField[] { Total.TOTAL.BIRTHDAY }, false);
        public static Index TOTAL_FLOAT_POPULATION = Internal.createIndex("float_population", Total.TOTAL, new OrderField[] { Total.TOTAL.FLOAT_POPULATION }, false);
        public static Index TOTAL_NAME = Internal.createIndex("name", Total.TOTAL, new OrderField[] { Total.TOTAL.NAME }, false);
        public static Index TOTAL_OFFLINETIME = Internal.createIndex("offlinetime", Total.TOTAL, new OrderField[] { Total.TOTAL.OFFLINETIME }, false);
        public static Index TOTAL_ONLINETIME = Internal.createIndex("onlinetime", Total.TOTAL, new OrderField[] { Total.TOTAL.ONLINETIME }, false);
        public static Index TOTAL_ONLINETIME_OFFLINETIME = Internal.createIndex("onlinetime_offlinetime", Total.TOTAL, new OrderField[] { Total.TOTAL.ONLINETIME, Total.TOTAL.OFFLINETIME }, false);
        public static Index TOTAL_PERSONID = Internal.createIndex("personid", Total.TOTAL, new OrderField[] { Total.TOTAL.PERSONID }, false);
        public static Index TOTAL_PRIMARY = Internal.createIndex("PRIMARY", Total.TOTAL, new OrderField[] { Total.TOTAL.ID }, true);
        public static Index TOTAL_SEX = Internal.createIndex("sex", Total.TOTAL, new OrderField[] { Total.TOTAL.SEX }, false);
    }
}
