/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo;


import cn.dyhack.barvisual.pojo.tables.Bars;
import cn.dyhack.barvisual.pojo.tables.BarsCopy;
import cn.dyhack.barvisual.pojo.tables.FloatPopulation;
import cn.dyhack.barvisual.pojo.tables.Persons;
import cn.dyhack.barvisual.pojo.tables.Province;
import cn.dyhack.barvisual.pojo.tables.ProvinceId;
import cn.dyhack.barvisual.pojo.tables.Records;
import cn.dyhack.barvisual.pojo.tables.RecordsPersons;
import cn.dyhack.barvisual.pojo.tables.RecordsTime;
import cn.dyhack.barvisual.pojo.tables.SichuanProvince;
import cn.dyhack.barvisual.pojo.tables.Suspects;
import cn.dyhack.barvisual.pojo.tables.Total;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternetBarBackup extends SchemaImpl {

    private static final long serialVersionUID = 2020291399;

    /**
     * The reference instance of <code>internet_bar_backup</code>
     */
    public static final InternetBarBackup INTERNET_BAR_BACKUP = new InternetBarBackup();

    /**
     * The table <code>internet_bar_backup.bars</code>.
     */
    public final Bars BARS = cn.dyhack.barvisual.pojo.tables.Bars.BARS;

    /**
     * The table <code>internet_bar_backup.bars_copy</code>.
     */
    public final BarsCopy BARS_COPY = cn.dyhack.barvisual.pojo.tables.BarsCopy.BARS_COPY;

    /**
     * The table <code>internet_bar_backup.float_population</code>.
     */
    public final FloatPopulation FLOAT_POPULATION = cn.dyhack.barvisual.pojo.tables.FloatPopulation.FLOAT_POPULATION;

    /**
     * The table <code>internet_bar_backup.persons</code>.
     */
    public final Persons PERSONS = cn.dyhack.barvisual.pojo.tables.Persons.PERSONS;

    /**
     * The table <code>internet_bar_backup.province</code>.
     */
    public final Province PROVINCE = cn.dyhack.barvisual.pojo.tables.Province.PROVINCE;

    /**
     * The table <code>internet_bar_backup.province_id</code>.
     */
    public final ProvinceId PROVINCE_ID = cn.dyhack.barvisual.pojo.tables.ProvinceId.PROVINCE_ID;

    /**
     * The table <code>internet_bar_backup.records</code>.
     */
    public final Records RECORDS = cn.dyhack.barvisual.pojo.tables.Records.RECORDS;

    /**
     * The table <code>internet_bar_backup.records_persons</code>.
     */
    public final RecordsPersons RECORDS_PERSONS = cn.dyhack.barvisual.pojo.tables.RecordsPersons.RECORDS_PERSONS;

    /**
     * The table <code>internet_bar_backup.records_time</code>.
     */
    public final RecordsTime RECORDS_TIME = cn.dyhack.barvisual.pojo.tables.RecordsTime.RECORDS_TIME;

    /**
     * The table <code>internet_bar_backup.sichuan_province</code>.
     */
    public final SichuanProvince SICHUAN_PROVINCE = cn.dyhack.barvisual.pojo.tables.SichuanProvince.SICHUAN_PROVINCE;

    /**
     * The table <code>internet_bar_backup.suspects</code>.
     */
    public final Suspects SUSPECTS = cn.dyhack.barvisual.pojo.tables.Suspects.SUSPECTS;

    /**
     * The table <code>internet_bar_backup.total</code>.
     */
    public final Total TOTAL = cn.dyhack.barvisual.pojo.tables.Total.TOTAL;

    /**
     * No further instances allowed
     */
    private InternetBarBackup() {
        super("internet_bar_backup", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Bars.BARS,
            BarsCopy.BARS_COPY,
            FloatPopulation.FLOAT_POPULATION,
            Persons.PERSONS,
            Province.PROVINCE,
            ProvinceId.PROVINCE_ID,
            Records.RECORDS,
            RecordsPersons.RECORDS_PERSONS,
            RecordsTime.RECORDS_TIME,
            SichuanProvince.SICHUAN_PROVINCE,
            Suspects.SUSPECTS,
            Total.TOTAL);
    }
}
