/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo;


import cn.dyhack.barvisual.pojo.tables.Bars;
import cn.dyhack.barvisual.pojo.tables.BarsCopy;
import cn.dyhack.barvisual.pojo.tables.FloatPopulation;
import cn.dyhack.barvisual.pojo.tables.Persons;
import cn.dyhack.barvisual.pojo.tables.Province;
import cn.dyhack.barvisual.pojo.tables.ProvinceId;
import cn.dyhack.barvisual.pojo.tables.Records;
import cn.dyhack.barvisual.pojo.tables.RecordsPersons;
import cn.dyhack.barvisual.pojo.tables.RecordsTime;
import cn.dyhack.barvisual.pojo.tables.SichuanProvince;
import cn.dyhack.barvisual.pojo.tables.Suspects;
import cn.dyhack.barvisual.pojo.tables.Total;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in internet_bar_backup
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>internet_bar_backup.bars</code>.
     */
    public static final Bars BARS = cn.dyhack.barvisual.pojo.tables.Bars.BARS;

    /**
     * The table <code>internet_bar_backup.bars_copy</code>.
     */
    public static final BarsCopy BARS_COPY = cn.dyhack.barvisual.pojo.tables.BarsCopy.BARS_COPY;

    /**
     * The table <code>internet_bar_backup.float_population</code>.
     */
    public static final FloatPopulation FLOAT_POPULATION = cn.dyhack.barvisual.pojo.tables.FloatPopulation.FLOAT_POPULATION;

    /**
     * The table <code>internet_bar_backup.persons</code>.
     */
    public static final Persons PERSONS = cn.dyhack.barvisual.pojo.tables.Persons.PERSONS;

    /**
     * The table <code>internet_bar_backup.province</code>.
     */
    public static final Province PROVINCE = cn.dyhack.barvisual.pojo.tables.Province.PROVINCE;

    /**
     * The table <code>internet_bar_backup.province_id</code>.
     */
    public static final ProvinceId PROVINCE_ID = cn.dyhack.barvisual.pojo.tables.ProvinceId.PROVINCE_ID;

    /**
     * The table <code>internet_bar_backup.records</code>.
     */
    public static final Records RECORDS = cn.dyhack.barvisual.pojo.tables.Records.RECORDS;

    /**
     * The table <code>internet_bar_backup.records_persons</code>.
     */
    public static final RecordsPersons RECORDS_PERSONS = cn.dyhack.barvisual.pojo.tables.RecordsPersons.RECORDS_PERSONS;

    /**
     * The table <code>internet_bar_backup.records_time</code>.
     */
    public static final RecordsTime RECORDS_TIME = cn.dyhack.barvisual.pojo.tables.RecordsTime.RECORDS_TIME;

    /**
     * The table <code>internet_bar_backup.sichuan_province</code>.
     */
    public static final SichuanProvince SICHUAN_PROVINCE = cn.dyhack.barvisual.pojo.tables.SichuanProvince.SICHUAN_PROVINCE;

    /**
     * The table <code>internet_bar_backup.suspects</code>.
     */
    public static final Suspects SUSPECTS = cn.dyhack.barvisual.pojo.tables.Suspects.SUSPECTS;

    /**
     * The table <code>internet_bar_backup.total</code>.
     */
    public static final Total TOTAL = cn.dyhack.barvisual.pojo.tables.Total.TOTAL;
}
