/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.records;


import cn.dyhack.barvisual.pojo.tables.Bars;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BarsRecord extends UpdatableRecordImpl<BarsRecord> implements Record7<String, String, Double, Double, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1315707195;

    /**
     * Setter for <code>internet_bar_backup.bars.id</code>. 网吧ID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars.id</code>. 网吧ID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>internet_bar_backup.bars.name</code>. 网吧名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars.name</code>. 网吧名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>internet_bar_backup.bars.longitude</code>. 网吧经度
     */
    public void setLongitude(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars.longitude</code>. 网吧经度
     */
    public Double getLongitude() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>internet_bar_backup.bars.latitude</code>. 网吧维度
     */
    public void setLatitude(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars.latitude</code>. 网吧维度
     */
    public Double getLatitude() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>internet_bar_backup.bars.suspect_id_num</code>. 嫌疑身份证数量
     */
    public void setSuspectIdNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars.suspect_id_num</code>. 嫌疑身份证数量
     */
    public Integer getSuspectIdNum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>internet_bar_backup.bars.suspect_cuited_num</code>. 套用身份证的次数
     */
    public void setSuspectCuitedNum(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars.suspect_cuited_num</code>. 套用身份证的次数
     */
    public Integer getSuspectCuitedNum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>internet_bar_backup.bars.suspect_audit_num</code>.
     */
    public void setSuspectAuditNum(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars.suspect_audit_num</code>.
     */
    public Integer getSuspectAuditNum() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Double, Double, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Double, Double, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Bars.BARS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Bars.BARS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Bars.BARS.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Bars.BARS.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Bars.BARS.SUSPECT_ID_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Bars.BARS.SUSPECT_CUITED_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Bars.BARS.SUSPECT_AUDIT_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getSuspectIdNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getSuspectCuitedNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getSuspectAuditNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSuspectIdNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSuspectCuitedNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSuspectAuditNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsRecord value3(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsRecord value4(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsRecord value5(Integer value) {
        setSuspectIdNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsRecord value6(Integer value) {
        setSuspectCuitedNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsRecord value7(Integer value) {
        setSuspectAuditNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsRecord values(String value1, String value2, Double value3, Double value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BarsRecord
     */
    public BarsRecord() {
        super(Bars.BARS);
    }

    /**
     * Create a detached, initialised BarsRecord
     */
    public BarsRecord(String id, String name, Double longitude, Double latitude, Integer suspectIdNum, Integer suspectCuitedNum, Integer suspectAuditNum) {
        super(Bars.BARS);

        set(0, id);
        set(1, name);
        set(2, longitude);
        set(3, latitude);
        set(4, suspectIdNum);
        set(5, suspectCuitedNum);
        set(6, suspectAuditNum);
    }
}
