/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.records;


import cn.dyhack.barvisual.pojo.tables.BarsCopy;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BarsCopyRecord extends UpdatableRecordImpl<BarsCopyRecord> implements Record5<String, String, Double, Double, Integer> {

    private static final long serialVersionUID = -1071616195;

    /**
     * Setter for <code>internet_bar_backup.bars_copy.id</code>. 网吧ID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars_copy.id</code>. 网吧ID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>internet_bar_backup.bars_copy.name</code>. 网吧名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars_copy.name</code>. 网吧名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>internet_bar_backup.bars_copy.longitude</code>. 网吧经度
     */
    public void setLongitude(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars_copy.longitude</code>. 网吧经度
     */
    public Double getLongitude() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>internet_bar_backup.bars_copy.latitude</code>. 网吧维度
     */
    public void setLatitude(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars_copy.latitude</code>. 网吧维度
     */
    public Double getLatitude() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>internet_bar_backup.bars_copy.suspect_id_num</code>. 嫌疑身份证数量
     */
    public void setSuspectIdNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>internet_bar_backup.bars_copy.suspect_id_num</code>. 嫌疑身份证数量
     */
    public Integer getSuspectIdNum() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Double, Double, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Double, Double, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BarsCopy.BARS_COPY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BarsCopy.BARS_COPY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return BarsCopy.BARS_COPY.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return BarsCopy.BARS_COPY.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return BarsCopy.BARS_COPY.SUSPECT_ID_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getSuspectIdNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSuspectIdNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsCopyRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsCopyRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsCopyRecord value3(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsCopyRecord value4(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsCopyRecord value5(Integer value) {
        setSuspectIdNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarsCopyRecord values(String value1, String value2, Double value3, Double value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BarsCopyRecord
     */
    public BarsCopyRecord() {
        super(BarsCopy.BARS_COPY);
    }

    /**
     * Create a detached, initialised BarsCopyRecord
     */
    public BarsCopyRecord(String id, String name, Double longitude, Double latitude, Integer suspectIdNum) {
        super(BarsCopy.BARS_COPY);

        set(0, id);
        set(1, name);
        set(2, longitude);
        set(3, latitude);
        set(4, suspectIdNum);
    }
}
