/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.records;


import cn.dyhack.barvisual.pojo.tables.Persons;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonsRecord extends UpdatableRecordImpl<PersonsRecord> implements Record5<String, String, Byte, String, Long> {

    private static final long serialVersionUID = -483607091;

    /**
     * Setter for <code>internet_bar_backup.persons.id</code>. 上网人编号
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>internet_bar_backup.persons.id</code>. 上网人编号
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>internet_bar_backup.persons.name</code>. 上网人名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>internet_bar_backup.persons.name</code>. 上网人名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>internet_bar_backup.persons.sex</code>. 上网人性别
     */
    public void setSex(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>internet_bar_backup.persons.sex</code>. 上网人性别
     */
    public Byte getSex() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>internet_bar_backup.persons.areaid</code>. 上网人籍贯
     */
    public void setAreaid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>internet_bar_backup.persons.areaid</code>. 上网人籍贯
     */
    public String getAreaid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>internet_bar_backup.persons.birthday</code>. 上网人出身时间戳
     */
    public void setBirthday(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>internet_bar_backup.persons.birthday</code>. 上网人出身时间戳
     */
    public Long getBirthday() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Byte, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Byte, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Persons.PERSONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Persons.PERSONS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Persons.PERSONS.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Persons.PERSONS.AREAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Persons.PERSONS.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAreaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAreaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord value3(Byte value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord value4(String value) {
        setAreaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord value5(Long value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord values(String value1, String value2, Byte value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonsRecord
     */
    public PersonsRecord() {
        super(Persons.PERSONS);
    }

    /**
     * Create a detached, initialised PersonsRecord
     */
    public PersonsRecord(String id, String name, Byte sex, String areaid, Long birthday) {
        super(Persons.PERSONS);

        set(0, id);
        set(1, name);
        set(2, sex);
        set(3, areaid);
        set(4, birthday);
    }
}
