/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.records;


import cn.dyhack.barvisual.pojo.tables.Province;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinceRecord extends UpdatableRecordImpl<ProvinceRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 592502309;

    /**
     * Setter for <code>internet_bar_backup.province.areaid</code>.
     */
    public void setAreaid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>internet_bar_backup.province.areaid</code>.
     */
    public Integer getAreaid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>internet_bar_backup.province.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>internet_bar_backup.province.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Province.PROVINCE.AREAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Province.PROVINCE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getAreaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getAreaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceRecord value1(Integer value) {
        setAreaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProvinceRecord
     */
    public ProvinceRecord() {
        super(Province.PROVINCE);
    }

    /**
     * Create a detached, initialised ProvinceRecord
     */
    public ProvinceRecord(Integer areaid, String name) {
        super(Province.PROVINCE);

        set(0, areaid);
        set(1, name);
    }
}
