/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.records;


import cn.dyhack.barvisual.pojo.tables.ProvinceId;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinceIdRecord extends TableRecordImpl<ProvinceIdRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1512752079;

    /**
     * Setter for <code>internet_bar_backup.province_id.province_id</code>.
     */
    public void setProvinceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>internet_bar_backup.province_id.province_id</code>.
     */
    public Integer getProvinceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>internet_bar_backup.province_id.province_name</code>. 省的名字
     */
    public void setProvinceName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>internet_bar_backup.province_id.province_name</code>. 省的名字
     */
    public String getProvinceName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProvinceId.PROVINCE_ID.PROVINCE_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProvinceId.PROVINCE_ID.PROVINCE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getProvinceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProvinceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProvinceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProvinceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceIdRecord value1(Integer value) {
        setProvinceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceIdRecord value2(String value) {
        setProvinceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceIdRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProvinceIdRecord
     */
    public ProvinceIdRecord() {
        super(ProvinceId.PROVINCE_ID);
    }

    /**
     * Create a detached, initialised ProvinceIdRecord
     */
    public ProvinceIdRecord(Integer provinceId, String provinceName) {
        super(ProvinceId.PROVINCE_ID);

        set(0, provinceId);
        set(1, provinceName);
    }
}
