/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.records;


import cn.dyhack.barvisual.pojo.tables.RecordsTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecordsTimeRecord extends TableRecordImpl<RecordsTimeRecord> implements Record4<String, String, Long, Integer> {

    private static final long serialVersionUID = -1935565348;

    /**
     * Setter for <code>internet_bar_backup.records_time.barid</code>.
     */
    public void setBarid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_time.barid</code>.
     */
    public String getBarid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>internet_bar_backup.records_time.personid</code>.
     */
    public void setPersonid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_time.personid</code>.
     */
    public String getPersonid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>internet_bar_backup.records_time.internet_time</code>.
     */
    public void setInternetTime(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_time.internet_time</code>.
     */
    public Long getInternetTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>internet_bar_backup.records_time.estimated_time</code>.
     */
    public void setEstimatedTime(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_time.estimated_time</code>.
     */
    public Integer getEstimatedTime() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Long, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Long, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return RecordsTime.RECORDS_TIME.BARID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RecordsTime.RECORDS_TIME.PERSONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return RecordsTime.RECORDS_TIME.INTERNET_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return RecordsTime.RECORDS_TIME.ESTIMATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getBarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPersonid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getInternetTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getEstimatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPersonid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getInternetTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getEstimatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsTimeRecord value1(String value) {
        setBarid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsTimeRecord value2(String value) {
        setPersonid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsTimeRecord value3(Long value) {
        setInternetTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsTimeRecord value4(Integer value) {
        setEstimatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsTimeRecord values(String value1, String value2, Long value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecordsTimeRecord
     */
    public RecordsTimeRecord() {
        super(RecordsTime.RECORDS_TIME);
    }

    /**
     * Create a detached, initialised RecordsTimeRecord
     */
    public RecordsTimeRecord(String barid, String personid, Long internetTime, Integer estimatedTime) {
        super(RecordsTime.RECORDS_TIME);

        set(0, barid);
        set(1, personid);
        set(2, internetTime);
        set(3, estimatedTime);
    }
}
