/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.records;


import cn.dyhack.barvisual.pojo.tables.RecordsPersons;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecordsPersonsRecord extends TableRecordImpl<RecordsPersonsRecord> implements Record6<String, String, String, Byte, String, Long> {

    private static final long serialVersionUID = 522096816;

    /**
     * Setter for <code>internet_bar_backup.records_persons.personid</code>.
     */
    public void setPersonid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_persons.personid</code>.
     */
    public String getPersonid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>internet_bar_backup.records_persons.barid</code>.
     */
    public void setBarid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_persons.barid</code>.
     */
    public String getBarid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>internet_bar_backup.records_persons.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_persons.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>internet_bar_backup.records_persons.sex</code>.
     */
    public void setSex(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_persons.sex</code>.
     */
    public Byte getSex() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>internet_bar_backup.records_persons.areaid</code>.
     */
    public void setAreaid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_persons.areaid</code>.
     */
    public String getAreaid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>internet_bar_backup.records_persons.birthday</code>.
     */
    public void setBirthday(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>internet_bar_backup.records_persons.birthday</code>.
     */
    public Long getBirthday() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Byte, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Byte, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return RecordsPersons.RECORDS_PERSONS.PERSONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RecordsPersons.RECORDS_PERSONS.BARID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RecordsPersons.RECORDS_PERSONS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return RecordsPersons.RECORDS_PERSONS.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RecordsPersons.RECORDS_PERSONS.AREAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return RecordsPersons.RECORDS_PERSONS.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPersonid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAreaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPersonid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAreaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsPersonsRecord value1(String value) {
        setPersonid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsPersonsRecord value2(String value) {
        setBarid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsPersonsRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsPersonsRecord value4(Byte value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsPersonsRecord value5(String value) {
        setAreaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsPersonsRecord value6(Long value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsPersonsRecord values(String value1, String value2, String value3, Byte value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecordsPersonsRecord
     */
    public RecordsPersonsRecord() {
        super(RecordsPersons.RECORDS_PERSONS);
    }

    /**
     * Create a detached, initialised RecordsPersonsRecord
     */
    public RecordsPersonsRecord(String personid, String barid, String name, Byte sex, String areaid, Long birthday) {
        super(RecordsPersons.RECORDS_PERSONS);

        set(0, personid);
        set(1, barid);
        set(2, name);
        set(3, sex);
        set(4, areaid);
        set(5, birthday);
    }
}
