/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.records;


import cn.dyhack.barvisual.pojo.tables.Total;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TotalRecord extends UpdatableRecordImpl<TotalRecord> implements Record10<Integer, String, String, String, String, Long, Long, Integer, Long, Byte> {

    private static final long serialVersionUID = -255744027;

    /**
     * Setter for <code>internet_bar_backup.total.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>internet_bar_backup.total.personid</code>.
     */
    public void setPersonid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.personid</code>.
     */
    public String getPersonid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>internet_bar_backup.total.barid</code>.
     */
    public void setBarid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.barid</code>.
     */
    public String getBarid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>internet_bar_backup.total.sex</code>.
     */
    public void setSex(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.sex</code>.
     */
    public String getSex() {
        return (String) get(3);
    }

    /**
     * Setter for <code>internet_bar_backup.total.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>internet_bar_backup.total.onlinetime</code>.
     */
    public void setOnlinetime(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.onlinetime</code>.
     */
    public Long getOnlinetime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>internet_bar_backup.total.offlinetime</code>.
     */
    public void setOfflinetime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.offlinetime</code>.
     */
    public Long getOfflinetime() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>internet_bar_backup.total.areaid</code>.
     */
    public void setAreaid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.areaid</code>.
     */
    public Integer getAreaid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>internet_bar_backup.total.birthday</code>.
     */
    public void setBirthday(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.birthday</code>.
     */
    public Long getBirthday() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>internet_bar_backup.total.float_population</code>.
     */
    public void setFloatPopulation(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>internet_bar_backup.total.float_population</code>.
     */
    public Byte getFloatPopulation() {
        return (Byte) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Long, Long, Integer, Long, Byte> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Long, Long, Integer, Long, Byte> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Total.TOTAL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Total.TOTAL.PERSONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Total.TOTAL.BARID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Total.TOTAL.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Total.TOTAL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Total.TOTAL.ONLINETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Total.TOTAL.OFFLINETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Total.TOTAL.AREAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Total.TOTAL.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return Total.TOTAL.FLOAT_POPULATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPersonid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getOnlinetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getOfflinetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getAreaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component10() {
        return getFloatPopulation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPersonid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getOnlinetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getOfflinetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getAreaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getFloatPopulation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value2(String value) {
        setPersonid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value3(String value) {
        setBarid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value4(String value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value5(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value6(Long value) {
        setOnlinetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value7(Long value) {
        setOfflinetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value8(Integer value) {
        setAreaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value9(Long value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord value10(Byte value) {
        setFloatPopulation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TotalRecord values(Integer value1, String value2, String value3, String value4, String value5, Long value6, Long value7, Integer value8, Long value9, Byte value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TotalRecord
     */
    public TotalRecord() {
        super(Total.TOTAL);
    }

    /**
     * Create a detached, initialised TotalRecord
     */
    public TotalRecord(Integer id, String personid, String barid, String sex, String name, Long onlinetime, Long offlinetime, Integer areaid, Long birthday, Byte floatPopulation) {
        super(Total.TOTAL);

        set(0, id);
        set(1, personid);
        set(2, barid);
        set(3, sex);
        set(4, name);
        set(5, onlinetime);
        set(6, offlinetime);
        set(7, areaid);
        set(8, birthday);
        set(9, floatPopulation);
    }
}
