/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables;


import cn.dyhack.barvisual.pojo.Indexes;
import cn.dyhack.barvisual.pojo.InternetBarBackup;
import cn.dyhack.barvisual.pojo.Keys;
import cn.dyhack.barvisual.pojo.tables.records.BarsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bars extends TableImpl<BarsRecord> {

    private static final long serialVersionUID = 1717331939;

    /**
     * The reference instance of <code>internet_bar_backup.bars</code>
     */
    public static final Bars BARS = new Bars();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BarsRecord> getRecordType() {
        return BarsRecord.class;
    }

    /**
     * The column <code>internet_bar_backup.bars.id</code>. 网吧ID
     */
    public final TableField<BarsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "网吧ID");

    /**
     * The column <code>internet_bar_backup.bars.name</code>. 网吧名称
     */
    public final TableField<BarsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "网吧名称");

    /**
     * The column <code>internet_bar_backup.bars.longitude</code>. 网吧经度
     */
    public final TableField<BarsRecord, Double> LONGITUDE = createField("longitude", org.jooq.impl.SQLDataType.DOUBLE, this, "网吧经度");

    /**
     * The column <code>internet_bar_backup.bars.latitude</code>. 网吧维度
     */
    public final TableField<BarsRecord, Double> LATITUDE = createField("latitude", org.jooq.impl.SQLDataType.DOUBLE, this, "网吧维度");

    /**
     * The column <code>internet_bar_backup.bars.suspect_id_num</code>. 嫌疑身份证数量
     */
    public final TableField<BarsRecord, Integer> SUSPECT_ID_NUM = createField("suspect_id_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "嫌疑身份证数量");

    /**
     * The column <code>internet_bar_backup.bars.suspect_cuited_num</code>. 套用身份证的次数
     */
    public final TableField<BarsRecord, Integer> SUSPECT_CUITED_NUM = createField("suspect_cuited_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "套用身份证的次数");

    /**
     * The column <code>internet_bar_backup.bars.suspect_audit_num</code>.
     */
    public final TableField<BarsRecord, Integer> SUSPECT_AUDIT_NUM = createField("suspect_audit_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>internet_bar_backup.bars</code> table reference
     */
    public Bars() {
        this(DSL.name("bars"), null);
    }

    /**
     * Create an aliased <code>internet_bar_backup.bars</code> table reference
     */
    public Bars(String alias) {
        this(DSL.name(alias), BARS);
    }

    /**
     * Create an aliased <code>internet_bar_backup.bars</code> table reference
     */
    public Bars(Name alias) {
        this(alias, BARS);
    }

    private Bars(Name alias, Table<BarsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Bars(Name alias, Table<BarsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InternetBarBackup.INTERNET_BAR_BACKUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BARS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BarsRecord> getPrimaryKey() {
        return Keys.KEY_BARS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BarsRecord>> getKeys() {
        return Arrays.<UniqueKey<BarsRecord>>asList(Keys.KEY_BARS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Bars as(String alias) {
        return new Bars(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Bars as(Name alias) {
        return new Bars(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bars rename(String name) {
        return new Bars(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bars rename(Name name) {
        return new Bars(name, null);
    }
}
