/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables;


import cn.dyhack.barvisual.pojo.Indexes;
import cn.dyhack.barvisual.pojo.InternetBarBackup;
import cn.dyhack.barvisual.pojo.tables.records.RecordsTimeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecordsTime extends TableImpl<RecordsTimeRecord> {

    private static final long serialVersionUID = -1922354906;

    /**
     * The reference instance of <code>internet_bar_backup.records_time</code>
     */
    public static final RecordsTime RECORDS_TIME = new RecordsTime();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecordsTimeRecord> getRecordType() {
        return RecordsTimeRecord.class;
    }

    /**
     * The column <code>internet_bar_backup.records_time.barid</code>.
     */
    public final TableField<RecordsTimeRecord, String> BARID = createField("barid", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>internet_bar_backup.records_time.personid</code>.
     */
    public final TableField<RecordsTimeRecord, String> PERSONID = createField("personid", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>internet_bar_backup.records_time.internet_time</code>.
     */
    public final TableField<RecordsTimeRecord, Long> INTERNET_TIME = createField("internet_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>internet_bar_backup.records_time.estimated_time</code>.
     */
    public final TableField<RecordsTimeRecord, Integer> ESTIMATED_TIME = createField("estimated_time", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>internet_bar_backup.records_time</code> table reference
     */
    public RecordsTime() {
        this(DSL.name("records_time"), null);
    }

    /**
     * Create an aliased <code>internet_bar_backup.records_time</code> table reference
     */
    public RecordsTime(String alias) {
        this(DSL.name(alias), RECORDS_TIME);
    }

    /**
     * Create an aliased <code>internet_bar_backup.records_time</code> table reference
     */
    public RecordsTime(Name alias) {
        this(alias, RECORDS_TIME);
    }

    private RecordsTime(Name alias, Table<RecordsTimeRecord> aliased) {
        this(alias, aliased, null);
    }

    private RecordsTime(Name alias, Table<RecordsTimeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InternetBarBackup.INTERNET_BAR_BACKUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RECORDS_TIME_BARID, Indexes.RECORDS_TIME_INTERNET_TIME, Indexes.RECORDS_TIME_PERSONID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsTime as(String alias) {
        return new RecordsTime(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecordsTime as(Name alias) {
        return new RecordsTime(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RecordsTime rename(String name) {
        return new RecordsTime(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecordsTime rename(Name name) {
        return new RecordsTime(name, null);
    }
}
