/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.daos;


import cn.dyhack.barvisual.pojo.tables.Persons;
import cn.dyhack.barvisual.pojo.tables.records.PersonsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonsDao extends DAOImpl<PersonsRecord, cn.dyhack.barvisual.pojo.tables.pojos.Persons, String> {

    /**
     * Create a new PersonsDao without any configuration
     */
    public PersonsDao() {
        super(Persons.PERSONS, cn.dyhack.barvisual.pojo.tables.pojos.Persons.class);
    }

    /**
     * Create a new PersonsDao with an attached configuration
     */
    public PersonsDao(Configuration configuration) {
        super(Persons.PERSONS, cn.dyhack.barvisual.pojo.tables.pojos.Persons.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.dyhack.barvisual.pojo.tables.pojos.Persons object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.dyhack.barvisual.pojo.tables.pojos.Persons> fetchById(String... values) {
        return fetch(Persons.PERSONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.dyhack.barvisual.pojo.tables.pojos.Persons fetchOneById(String value) {
        return fetchOne(Persons.PERSONS.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<cn.dyhack.barvisual.pojo.tables.pojos.Persons> fetchByName(String... values) {
        return fetch(Persons.PERSONS.NAME, values);
    }

    /**
     * Fetch records that have <code>sex IN (values)</code>
     */
    public List<cn.dyhack.barvisual.pojo.tables.pojos.Persons> fetchBySex(Byte... values) {
        return fetch(Persons.PERSONS.SEX, values);
    }

    /**
     * Fetch records that have <code>areaid IN (values)</code>
     */
    public List<cn.dyhack.barvisual.pojo.tables.pojos.Persons> fetchByAreaid(String... values) {
        return fetch(Persons.PERSONS.AREAID, values);
    }

    /**
     * Fetch records that have <code>birthday IN (values)</code>
     */
    public List<cn.dyhack.barvisual.pojo.tables.pojos.Persons> fetchByBirthday(Long... values) {
        return fetch(Persons.PERSONS.BIRTHDAY, values);
    }
}
