/*
 * This file is generated by jOOQ.
*/
package cn.dyhack.barvisual.pojo.tables.daos;


import cn.dyhack.barvisual.pojo.tables.Suspects;
import cn.dyhack.barvisual.pojo.tables.records.SuspectsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuspectsDao extends DAOImpl<SuspectsRecord, cn.dyhack.barvisual.pojo.tables.pojos.Suspects, String> {

    /**
     * Create a new SuspectsDao without any configuration
     */
    public SuspectsDao() {
        super(Suspects.SUSPECTS, cn.dyhack.barvisual.pojo.tables.pojos.Suspects.class);
    }

    /**
     * Create a new SuspectsDao with an attached configuration
     */
    public SuspectsDao(Configuration configuration) {
        super(Suspects.SUSPECTS, cn.dyhack.barvisual.pojo.tables.pojos.Suspects.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.dyhack.barvisual.pojo.tables.pojos.Suspects object) {
        return object.getPersonid();
    }

    /**
     * Fetch records that have <code>personid IN (values)</code>
     */
    public List<cn.dyhack.barvisual.pojo.tables.pojos.Suspects> fetchByPersonid(String... values) {
        return fetch(Suspects.SUSPECTS.PERSONID, values);
    }

    /**
     * Fetch a unique record that has <code>personid = value</code>
     */
    public cn.dyhack.barvisual.pojo.tables.pojos.Suspects fetchOneByPersonid(String value) {
        return fetchOne(Suspects.SUSPECTS.PERSONID, value);
    }

    /**
     * Fetch records that have <code>count IN (values)</code>
     */
    public List<cn.dyhack.barvisual.pojo.tables.pojos.Suspects> fetchByCount(Integer... values) {
        return fetch(Suspects.SUSPECTS.COUNT, values);
    }
}
